import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  Plane, Upload, Sparkles, Share2, CheckCircle2,
  MapPin, Calendar, Clock, QrCode, FileText,
  History, Zap, ArrowRight, ChevronRight,
} from 'lucide-react';
import { Button } from '@/components/ui/button';

/* ── Animation helpers ─────────────────────────────────────── */
const fadeUp = (delay = 0) => ({
  initial: { opacity: 0, y: 24 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.6, delay, ease: [0.22, 1, 0.36, 1] },
});

const inView = (delay = 0) => ({
  initial: { opacity: 0, y: 28 },
  whileInView: { opacity: 1, y: 0 },
  viewport: { once: true, margin: '-60px' },
  transition: { duration: 0.6, delay, ease: [0.22, 1, 0.36, 1] },
});

/* ── Mock itinerary card data ──────────────────────────────── */
const MOCK_ACTIVITIES = [
  { time: '10:30', emoji: '✈️', title: 'Land at CDG Airport', tag: 'transport',   tagColor: 'bg-blue-100 text-blue-700'    },
  { time: '14:00', emoji: '🏨', title: 'Check-in · Le Marais Hotel', tag: 'hotel', tagColor: 'bg-emerald-100 text-emerald-700' },
  { time: '17:30', emoji: '🗼', title: 'Eiffel Tower sunset', tag: 'sightseeing', tagColor: 'bg-violet-100 text-violet-700'   },
  { time: '20:00', emoji: '🍷', title: 'Dinner at Café de Flore', tag: 'food',    tagColor: 'bg-amber-100 text-amber-700'    },
];

/* ── Data ──────────────────────────────────────────────────── */
const STATS = [
  { value: '50K+',  label: 'Trips Planned'    },
  { value: '4.9★',  label: 'User Rating'      },
  { value: '< 30s', label: 'Itinerary Ready'  },
  { value: '100%',  label: 'Free to Start'    },
];

const STEPS = [
  { n: '01', icon: Upload,       title: 'Upload documents',      desc: 'Drop flight tickets, hotel PDFs or booking images — any format works.'         },
  { n: '02', icon: Sparkles,     title: 'AI reads everything',   desc: 'Gemini Vision extracts dates, destinations, flights and hotels instantly.'      },
  { n: '03', icon: Calendar,     title: 'Itinerary generated',   desc: 'A full day-by-day plan with activities, tips and Google Maps links in seconds.' },
  { n: '04', icon: Share2,       title: 'Share anywhere',        desc: 'Send via link, QR code, WhatsApp or download a formatted PDF for offline use.'  },
];

const FEATURES = [
  { icon: FileText,    title: 'PDF & Image support',   desc: 'Upload scanned tickets, e-tickets or hotel PDFs — any format, up to 15 MB.'       },
  { icon: Sparkles,    title: 'Gemini AI extraction',  desc: 'Gemini Vision understands travel documents visually, not just as plain text.'      },
  { icon: MapPin,      title: 'Day-by-day planning',   desc: 'Activities, timings, insider tips and Google Maps links for every single stop.'     },
  { icon: QrCode,      title: 'QR code sharing',       desc: 'Generate a QR code at the airport — your travel partner scans, no typing needed.'  },
  { icon: Plane,       title: 'Offline PDF export',    desc: 'Download a beautifully formatted PDF — no internet connection needed on the road.'  },
  { icon: History,     title: 'Full trip history',     desc: 'Every itinerary saved forever. Re-open, re-share or regenerate with one click.'     },
];

/* ── Sub-components ────────────────────────────────────────── */
const MockCard = () => (
  <motion.div
    {...fadeUp(0.35)}
    animate={{ y: [0, -10, 0] }}
    transition={{ duration: 5, repeat: Infinity, ease: 'easeInOut', delay: 0.6 }}
    className="w-full max-w-sm rounded-2xl border border-white/10 bg-white/8 shadow-2xl shadow-black/40 backdrop-blur-md overflow-hidden"
  >
    {/* Card header */}
    <div className="bg-gradient-to-r from-blue-600 to-indigo-600 px-5 py-4">
      <div className="flex items-center justify-between">
        <div>
          <p className="text-xs font-medium text-blue-200 uppercase tracking-wider">Generated by TripCraft AI</p>
          <h3 className="mt-0.5 text-base font-bold text-white">Paris Adventure — 5 Days</h3>
        </div>
        <span className="text-2xl">🗼</span>
      </div>
      <div className="mt-2 flex items-center gap-3 text-xs text-blue-200">
        <span className="flex items-center gap-1"><Plane className="h-3 w-3" /> LHR → CDG</span>
        <span className="flex items-center gap-1"><Calendar className="h-3 w-3" /> Jun 12 – 17</span>
      </div>
    </div>

    {/* Day label */}
    <div className="border-b border-white/10 bg-white/5 px-5 py-2.5">
      <span className="text-xs font-semibold text-blue-300 uppercase tracking-wider">Day 1 — Arrival & First Impressions</span>
    </div>

    {/* Activities */}
    <div className="divide-y divide-white/8">
      {MOCK_ACTIVITIES.map((a) => (
        <div key={a.title} className="flex items-center gap-3 px-5 py-3">
          <span className="w-10 shrink-0 text-right text-xs font-mono text-blue-300/70">{a.time}</span>
          <span className="text-base leading-none">{a.emoji}</span>
          <div className="min-w-0 flex-1">
            <p className="truncate text-sm font-medium text-white">{a.title}</p>
          </div>
          <span className={`shrink-0 rounded-full px-2 py-0.5 text-[10px] font-semibold ${a.tagColor}`}>
            {a.tag}
          </span>
        </div>
      ))}
    </div>

    {/* Footer */}
    <div className="flex items-center justify-between border-t border-white/10 bg-white/5 px-5 py-3">
      <span className="text-xs text-blue-300/60">Day 2 · Art & Culture ↓</span>
      <span className="flex items-center gap-1 text-xs font-medium text-blue-400">
        View full plan <ChevronRight className="h-3 w-3" />
      </span>
    </div>
  </motion.div>
);

const StepCard = ({ step, i }) => (
  <motion.div {...inView(i * 0.1)} className="relative flex flex-col items-center text-center">
    {/* Connector line */}
    {i < STEPS.length - 1 && (
      <div className="absolute left-[calc(50%+3rem)] top-8 hidden h-px w-[calc(100%-4rem)] bg-gradient-to-r from-blue-200 to-transparent lg:block" />
    )}
    <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-2xl bg-blue-600 shadow-lg shadow-blue-600/30">
      <step.icon className="h-7 w-7 text-white" />
    </div>
    <span className="mb-1 text-xs font-bold tracking-widest text-blue-500">{step.n}</span>
    <h3 className="mb-2 text-base font-bold text-gray-900">{step.title}</h3>
    <p className="text-sm leading-relaxed text-gray-500">{step.desc}</p>
  </motion.div>
);

const FeatureCard = ({ f, i }) => (
  <motion.div
    {...inView(i * 0.07)}
    whileHover={{ y: -4, transition: { duration: 0.2 } }}
    className="group flex flex-col gap-4 rounded-2xl border border-gray-100 bg-white p-6 shadow-sm transition-shadow hover:shadow-md"
  >
    <div className="flex h-11 w-11 items-center justify-center rounded-xl bg-blue-50 transition-colors group-hover:bg-blue-100">
      <f.icon className="h-5 w-5 text-blue-600" />
    </div>
    <div>
      <h3 className="mb-1.5 font-bold text-gray-900">{f.title}</h3>
      <p className="text-sm leading-relaxed text-gray-500">{f.desc}</p>
    </div>
  </motion.div>
);

/* ── Page ──────────────────────────────────────────────────── */
const LandingPage = () => (
  <div className="flex flex-col">

    {/* ── HERO ── */}
    <section className="relative overflow-hidden bg-gradient-to-br from-slate-900 via-blue-950 to-indigo-900 px-4 pb-0 pt-20 sm:pt-28">

      {/* Background decoration */}
      <div className="pointer-events-none absolute inset-0 overflow-hidden">
        <div className="absolute -left-40 -top-40 h-[500px] w-[500px] rounded-full bg-blue-600/20 blur-3xl" />
        <div className="absolute right-0 top-1/3 h-96 w-96 rounded-full bg-indigo-500/20 blur-3xl" />
        <div className="absolute bottom-0 left-1/2 h-80 w-80 -translate-x-1/2 rounded-full bg-violet-600/15 blur-3xl" />
        <svg className="absolute inset-0 h-full w-full opacity-[0.04]" xmlns="http://www.w3.org/2000/svg">
          <defs>
            <pattern id="dots-lp" width="28" height="28" patternUnits="userSpaceOnUse">
              <circle cx="1.5" cy="1.5" r="1.5" fill="white" />
            </pattern>
          </defs>
          <rect width="100%" height="100%" fill="url(#dots-lp)" />
        </svg>
      </div>

      <div className="relative z-10 mx-auto max-w-6xl">
        <div className="flex flex-col items-center gap-16 lg:flex-row lg:items-center lg:gap-12">

          {/* Left: copy */}
          <div className="flex-1 text-center lg:text-left">
            <motion.div {...fadeUp(0)}>
              <span className="mb-6 inline-flex items-center gap-2 rounded-full border border-blue-400/30 bg-blue-500/15 px-4 py-1.5 text-sm font-medium text-blue-300">
                <Sparkles className="h-3.5 w-3.5" />
                Powered by Gemini AI
              </span>
            </motion.div>

            <motion.h1 {...fadeUp(0.08)} className="mb-5 text-4xl font-bold leading-tight tracking-tight text-white sm:text-5xl xl:text-6xl">
              Turn your bookings<br />into a{' '}
              <span className="bg-gradient-to-r from-blue-400 to-indigo-300 bg-clip-text text-transparent">
                perfect journey
              </span>
            </motion.h1>

            <motion.p {...fadeUp(0.16)} className="mb-8 max-w-lg text-base leading-relaxed text-blue-200/75 sm:text-lg lg:mx-0 mx-auto">
              Upload your flight tickets and hotel confirmations. TripCraft reads every document and builds a complete day-by-day itinerary — in under 30 seconds.
            </motion.p>

            <motion.div {...fadeUp(0.24)} className="flex flex-wrap justify-center gap-3 lg:justify-start">
              <Button size="lg" className="h-12 rounded-xl bg-blue-500 px-7 text-base font-semibold shadow-lg shadow-blue-500/30 hover:bg-blue-400" asChild>
                <Link to="/register">
                  Start for free <ArrowRight className="ml-1.5 h-4 w-4" />
                </Link>
              </Button>
              <Button size="lg" variant="outline" className="h-12 rounded-xl border-white/20 bg-white/8 px-7 text-base font-semibold text-white backdrop-blur-sm hover:bg-white/15" asChild>
                <Link to="/login">Sign in</Link>
              </Button>
            </motion.div>

            <motion.div {...fadeUp(0.32)} className="mt-8 flex flex-wrap justify-center gap-5 lg:justify-start">
              {['No credit card', 'Free forever plan', '50K+ trips planned'].map((t) => (
                <span key={t} className="flex items-center gap-1.5 text-sm text-blue-300/70">
                  <CheckCircle2 className="h-3.5 w-3.5 text-blue-400" /> {t}
                </span>
              ))}
            </motion.div>
          </div>

          {/* Right: floating card */}
          <div className="flex w-full flex-1 justify-center lg:justify-end">
            <MockCard />
          </div>
        </div>

        {/* Stats bar */}
        <motion.div {...fadeUp(0.45)} className="mt-16 grid grid-cols-2 divide-x divide-white/10 overflow-hidden rounded-2xl border border-white/10 bg-white/6 backdrop-blur-sm sm:grid-cols-4">
          {STATS.map((s) => (
            <div key={s.label} className="py-5 text-center">
              <p className="text-xl font-bold text-white sm:text-2xl">{s.value}</p>
              <p className="mt-0.5 text-xs text-blue-300/60">{s.label}</p>
            </div>
          ))}
        </motion.div>
      </div>

      {/* Bottom curve */}
      <div className="relative z-10 mt-16 h-10 w-full">
        <svg viewBox="0 0 1440 40" className="absolute bottom-0 w-full" preserveAspectRatio="none" fill="white">
          <path d="M0,40 C360,0 1080,0 1440,40 L1440,40 L0,40 Z" />
        </svg>
      </div>
    </section>

    {/* ── HOW IT WORKS ── */}
    <section className="bg-white px-4 py-20 sm:py-28">
      <div className="mx-auto max-w-6xl">
        <motion.div {...inView()} className="mb-14 text-center">
          <span className="mb-3 block text-xs font-bold uppercase tracking-widest text-blue-500">The process</span>
          <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
            From documents to itinerary<br className="hidden sm:block" /> in four steps
          </h2>
        </motion.div>

        <div className="grid gap-10 sm:grid-cols-2 lg:grid-cols-4">
          {STEPS.map((step, i) => <StepCard key={step.n} step={step} i={i} />)}
        </div>
      </div>
    </section>

    {/* ── FEATURES ── */}
    <section className="bg-gray-50/70 px-4 py-20 sm:py-28">
      <div className="mx-auto max-w-6xl">
        <motion.div {...inView()} className="mb-14 text-center">
          <span className="mb-3 block text-xs font-bold uppercase tracking-widest text-blue-500">Features</span>
          <h2 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl">
            Everything you need for <br className="hidden sm:block" />
            <span className="text-blue-600">perfect trip planning</span>
          </h2>
          <p className="mx-auto mt-4 max-w-xl text-base text-gray-500">
            Built for travellers who want detailed, shareable itineraries without the hours of manual planning.
          </p>
        </motion.div>

        <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">
          {FEATURES.map((f, i) => <FeatureCard key={f.title} f={f} i={i} />)}
        </div>
      </div>
    </section>

    {/* ── CTA ── */}
    <section className="relative overflow-hidden bg-gradient-to-br from-slate-900 via-blue-950 to-indigo-900 px-4 py-20 sm:py-28">
      <div className="pointer-events-none absolute inset-0">
        <div className="absolute -bottom-20 -left-20 h-80 w-80 rounded-full bg-blue-600/20 blur-3xl" />
        <div className="absolute -right-20 -top-20 h-80 w-80 rounded-full bg-indigo-500/20 blur-3xl" />
      </div>
      <div className="relative z-10 mx-auto max-w-2xl text-center">
        <motion.div {...inView()}>
          <span className="mb-5 inline-flex items-center gap-2 rounded-full border border-blue-400/30 bg-blue-500/15 px-4 py-1.5 text-sm font-medium text-blue-300">
            <Zap className="h-3.5 w-3.5" /> Get started in 60 seconds
          </span>
          <h2 className="mb-4 text-3xl font-bold text-white sm:text-4xl">
            Ready to plan your <br />
            <span className="bg-gradient-to-r from-blue-400 to-indigo-300 bg-clip-text text-transparent">
              next adventure?
            </span>
          </h2>
          <p className="mb-8 text-base text-blue-200/70">
            Join 50,000+ travellers who use TripCraft to turn their booking confirmations into beautiful, shareable itineraries.
          </p>
          <div className="flex flex-wrap justify-center gap-3">
            <Button size="lg" className="h-12 rounded-xl bg-blue-500 px-8 text-base font-semibold shadow-lg shadow-blue-500/30 hover:bg-blue-400" asChild>
              <Link to="/register">Create your itinerary — it's free</Link>
            </Button>
          </div>
          <p className="mt-4 text-sm text-blue-300/50">No credit card required · Free forever plan</p>
        </motion.div>
      </div>
    </section>

    {/* ── FOOTER ── */}
    <footer className="border-t bg-white px-4 py-8">
      <div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-4 sm:flex-row">
        <div className="flex items-center gap-2 font-bold text-gray-800">
          <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-blue-600">
            <Plane className="h-3.5 w-3.5 text-white" />
          </div>
          TripCraft
        </div>
        <p className="text-sm text-gray-400">
          © {new Date().getFullYear()} TripCraft — AI Travel Itinerary Generator
        </p>
        <div className="flex gap-5 text-sm text-gray-400">
          <Link to="/login" className="hover:text-gray-600 transition-colors">Sign in</Link>
          <Link to="/register" className="hover:text-gray-600 transition-colors">Get started</Link>
        </div>
      </div>
    </footer>
  </div>
);

export default LandingPage;
