import { PDFDownloadLink, Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import { Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { fmtDate } from '@/utils/formatDate';

const styles = StyleSheet.create({
  page: { padding: 40, fontFamily: 'Helvetica', fontSize: 10, color: '#1a1a1a' },
  header: { marginBottom: 20, borderBottom: '2px solid #3b82f6', paddingBottom: 12 },
  title: { fontSize: 22, fontFamily: 'Helvetica-Bold', color: '#1d4ed8', marginBottom: 4 },
  subtitle: { fontSize: 10, color: '#6b7280' },
  dayBlock: { marginTop: 14 },
  dayHeader: { fontSize: 13, fontFamily: 'Helvetica-Bold', color: '#1d4ed8', marginBottom: 6 },
  dayTheme: { fontSize: 9, color: '#6b7280', marginBottom: 8 },
  activity: { marginBottom: 8, paddingLeft: 12, borderLeft: '2px solid #dbeafe' },
  activityTitle: { fontSize: 10, fontFamily: 'Helvetica-Bold' },
  activityTime: { fontSize: 8, color: '#6b7280' },
  activityDesc: { fontSize: 9, color: '#374151', marginTop: 2, lineHeight: 1.4 },
  activityTip: { fontSize: 8, color: '#92400e', marginTop: 2, fontStyle: 'italic' },
  footer: { position: 'absolute', bottom: 20, left: 40, right: 40, textAlign: 'center', fontSize: 8, color: '#9ca3af' },
});

const ItineraryPDF = ({ itinerary }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>{itinerary.tripSummary?.title || 'Travel Itinerary'}</Text>
        <Text style={styles.subtitle}>
          {itinerary.tripSummary?.origin} → {itinerary.tripSummary?.destination}
          {itinerary.tripSummary?.startDate ? `  |  ${fmtDate(itinerary.tripSummary.startDate)} – ${fmtDate(itinerary.tripSummary.endDate)}` : ''}
          {itinerary.tripSummary?.totalDays ? `  |  ${itinerary.tripSummary.totalDays} Days` : ''}
        </Text>
      </View>

      {itinerary.days?.map((day) => (
        <View key={day.dayNumber} style={styles.dayBlock}>
          <Text style={styles.dayHeader}>Day {day.dayNumber} — {day.theme || ''}</Text>
          {day.date && <Text style={styles.dayTheme}>{fmtDate(day.date, 'EEEE, MMMM d yyyy')}</Text>}
          {day.activities?.map((act, i) => (
            <View key={i} style={styles.activity}>
              <Text style={styles.activityTime}>{act.time || ''}</Text>
              <Text style={styles.activityTitle}>{act.title}</Text>
              {act.description && <Text style={styles.activityDesc}>{act.description}</Text>}
              {act.tip && <Text style={styles.activityTip}>Tip: {act.tip}</Text>}
            </View>
          ))}
        </View>
      ))}

      <Text style={styles.footer}>Generated by TripCraft — AI Travel Itinerary Planner</Text>
    </Page>
  </Document>
);

const ExportPDFButton = ({ itinerary }) => (
  <div className="space-y-4">
    <div className="rounded-lg border bg-muted/30 p-4 text-sm text-muted-foreground">
      <p className="font-medium text-foreground mb-1">Export as PDF</p>
      <p>Download a beautifully formatted PDF of your itinerary — works offline, perfect for travel.</p>
    </div>
    <PDFDownloadLink
      document={<ItineraryPDF itinerary={itinerary} />}
      fileName={`${itinerary.tripSummary?.title?.replace(/\s+/g, '-') || 'itinerary'}.pdf`}
    >
      {({ loading }) => (
        <Button className="w-full gap-2" disabled={loading}>
          <Download className="h-4 w-4" />
          {loading ? 'Preparing PDF…' : 'Download PDF'}
        </Button>
      )}
    </PDFDownloadLink>
  </div>
);

export default ExportPDFButton;
